set line 200 pagesize 1000 
col OWNER for a15
col INDEX_NAME for a25
col INDEX_TYPE for a10
col TABLE_OWNER for a15
col TABLE_NAME for a20
col DEGREE for a10
select OWNER, INDEX_NAME, INDEX_TYPE, TABLE_OWNER, TABLE_NAME, STATUS, NUM_ROWS, DEGREE, LAST_ANALYZED,LOGGING, VISIBILITY from dba_indexes where TABLE_OWNER='&TABLE_OWNER' and TABLE_NAME='&TABLE_NAME' order by TABLE_OWNER,INDEX_NAME;
col COLUMN_NAME for a30	
col INDEX_OWNER for a10
break on INDEX_NAME skip 1
select INDEX_OWNER,INDEX_NAME, COLUMN_NAME, COLUMN_POSITION from dba_ind_columns where TABLE_NAME='&TABLE_NAME' order by INDEX_OWNER, INDEX_NAME ,COLUMN_POSITION ;
