col TABLE_NAME for a30
col owner for a30
col COLUMN_NAME for a20
select OWNER, TABLE_NAME, COLUMN_NAME, SEGMENT_NAME, TABLESPACE_NAME, COMPRESSION, ENCRYPT, DEDUPLICATION from dba_lobs where SEGMENT_NAME='&SEGMENT_NAME';

